
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kone1
 */
public class Kirjautuminen extends javax.swing.JFrame {

    /**
     * Creates new form Kirjautuminen
     */
    public Kirjautuminen() {
        initComponents();
        // asetetaan otsikko ikkunalle
        this.setTitle("Kirjautuminen");
        // asetetaan ikkuna avautuman ruudun keskelle
        this.setLocationRelativeTo(null);
    }

    public void sulje() {
        //ikkunan sulkemis metodi
        WindowEvent winClosingEvent = new WindowEvent (this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbltunnus = new javax.swing.JLabel();
        jlblsalasana = new javax.swing.JLabel();
        jtxtTunnus = new javax.swing.JTextField();
        jbtnkirjaudu = new javax.swing.JButton();
        jchkSalasana = new javax.swing.JCheckBox();
        jpswSalasana = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbltunnus.setText("Tunnus:");

        jlblsalasana.setText("Salasana:");

        jbtnkirjaudu.setText("Kirjaudu");
        jbtnkirjaudu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnkirjauduActionPerformed(evt);
            }
        });

        jchkSalasana.setText("Näytä salasana");
        jchkSalasana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkSalasanaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tunnus: admin , Salasana: Kissa123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbltunnus)
                            .addComponent(jlblsalasana))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jpswSalasana, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jchkSalasana))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jtxtTunnus, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jbtnkirjaudu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbltunnus)
                    .addComponent(jtxtTunnus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblsalasana)
                    .addComponent(jchkSalasana)
                    .addComponent(jpswSalasana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnkirjaudu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnkirjauduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnkirjauduActionPerformed
        // asetetaan toimiva tunnus ja salasana
        String oikeatunnus = "admin";
        char oikeasalasana[] = {'K','i','s','s','a','1','2','3'};
        //haetaan käyttöliittymastä tunnus ja salasana
        String tunnus = jtxtTunnus.getText();
        char salasana[] = jpswSalasana.getPassword();
        //Verrataan annettua tunnusta ja salasanaa
        if (oikeatunnus.equals(tunnus) && Arrays.equals(oikeasalasana, salasana)) {
            //täytetään taulukko nollilla tietoturvasyistä
            Arrays.fill(oikeasalasana, '0');
            GUI harjoitus = new GUI(tunnus);
            harjoitus.setVisible(true);
            sulje();
        } else {
            JOptionPane.showMessageDialog(this,"Tunnus tai salasana on väärin. Yritä uudestaan");
            jpswSalasana.setText("");
            jtxtTunnus.setText("");
            jtxtTunnus.requestFocus();
            return;
        }
    }//GEN-LAST:event_jbtnkirjauduActionPerformed

    private void jchkSalasanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkSalasanaActionPerformed
        //jos valittu näytetään kirjoitettu salasana
        if (jchkSalasana.isSelected()) {
            jpswSalasana.setEchoChar((char)0);
            jchkSalasana.setSelected(true);
        } else {
            jpswSalasana.setEchoChar('*');
            jchkSalasana.setSelected(false);
        }
    }//GEN-LAST:event_jchkSalasanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kirjautuminen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kirjautuminen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnkirjaudu;
    private javax.swing.JCheckBox jchkSalasana;
    private javax.swing.JLabel jlblsalasana;
    private javax.swing.JLabel jlbltunnus;
    private javax.swing.JPasswordField jpswSalasana;
    private javax.swing.JTextField jtxtTunnus;
    // End of variables declaration//GEN-END:variables
}
